name: ASP.NET Core API CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Get source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build the project
      - name: Build project
        run: dotnet build --no-restore --configuration Release

      # 5️⃣ Run unit tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t shehan/realestate-api:${{ github.ref_name }} \
            -f ./RealEstate.API/Dockerfile \
            ./RealEstate.API


      # 7️⃣ Login to Docker Hub (MAIN branch only)
      - name: Login to Docker Hub
        if: github.ref_name == 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8️⃣ Push Docker image (MAIN branch only)
      - name: Push Docker image
        if: github.ref_name == 'main'
        run: |
          docker push shehanindrajith2002/realestate-api:main
